package space.zeroxv6.journex.desktop.ui.theme
import androidx.compose.ui.graphics.Color
data class AppColorScheme(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val background: Color,
    val surface: Color,
    val surfaceVariant: Color,
    val surfaceTertiary: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textDisabled: Color,
    val border: Color,
    val borderFocused: Color,
    val divider: Color,
    val interactive: Color,
    val interactiveHover: Color,
    val interactivePressed: Color,
    val success: Color,
    val error: Color,
    val warning: Color,
    val info: Color,
    val cardBackground: Color,
    val cardBackgroundHover: Color,
    val inputBackground: Color,
    val selectedBackground: Color,
    val overlayBackground: Color
)
val ClassicWhiteScheme = AppColorScheme(
    primary = Color.Black,
    onPrimary = Color.White,
    primaryContainer = Color(0xFF424242),
    background = Color.White,
    surface = Color(0xFFFAFAFA),
    surfaceVariant = Color(0xFFF5F5F5),
    surfaceTertiary = Color(0xFFEEEEEE),
    textPrimary = Color.Black,
    textSecondary = Color(0xFF424242),
    textTertiary = Color(0xFF616161),
    textDisabled = Color(0xFF9E9E9E),
    border = Color(0xFFE0E0E0),
    borderFocused = Color(0xFFBDBDBD),
    divider = Color(0xFFEEEEEE),
    interactive = Color.Black,
    interactiveHover = Color(0xFF424242),
    interactivePressed = Color(0xFF424242),
    success = Color(0xFF4CAF50),
    error = Color(0xFFB00020),
    warning = Color(0xFFFFA726),
    info = Color(0xFF2196F3),
    cardBackground = Color(0xFFFAFAFA),
    cardBackgroundHover = Color(0xFFF5F5F5),
    inputBackground = Color(0xFFF5F5F5),
    selectedBackground = Color(0xFFF0F0F0),
    overlayBackground = Color(0x80000000)
)
val WarmCreamScheme = AppColorScheme(
    primary = Color(0xFF3E2723),
    onPrimary = Color(0xFFFFF8E1),
    primaryContainer = Color(0xFF5D4037),
    background = Color(0xFFFFF8E1),
    surface = Color(0xFFFFF3E0),
    surfaceVariant = Color(0xFFFFECB3),
    surfaceTertiary = Color(0xFFFFE082),
    textPrimary = Color(0xFF3E2723),
    textSecondary = Color(0xFF5D4037),
    textTertiary = Color(0xFF795548),
    textDisabled = Color(0xFF8D6E63),
    border = Color(0xFFFFE082),
    borderFocused = Color(0xFFFFD54F),
    divider = Color(0xFFFFECB3),
    interactive = Color(0xFF3E2723),
    interactiveHover = Color(0xFF5D4037),
    interactivePressed = Color(0xFF795548),
    success = Color(0xFF66BB6A),
    error = Color(0xFFEF5350),
    warning = Color(0xFFFFB74D),
    info = Color(0xFF42A5F5),
    cardBackground = Color(0xFFFFF3E0),
    cardBackgroundHover = Color(0xFFFFECB3),
    inputBackground = Color(0xFFFFECB3),
    selectedBackground = Color(0xFFFFE082),
    overlayBackground = Color(0x803E2723)
)
val DarkGrayScheme = AppColorScheme(
    primary = Color(0xFF90CAF9),
    onPrimary = Color(0xFF212121),
    primaryContainer = Color(0xFF64B5F6),
    background = Color(0xFF303030),
    surface = Color(0xFF3A3A3A),
    surfaceVariant = Color(0xFF424242),
    surfaceTertiary = Color(0xFF4A4A4A),
    textPrimary = Color(0xFFEEEEEE),
    textSecondary = Color(0xFFBDBDBD),
    textTertiary = Color(0xFF9E9E9E),
    textDisabled = Color(0xFF757575),
    border = Color(0xFF5A5A5A),
    borderFocused = Color(0xFF757575),
    divider = Color(0xFF4A4A4A),
    interactive = Color(0xFF90CAF9),
    interactiveHover = Color(0xFF64B5F6),
    interactivePressed = Color(0xFF42A5F5),
    success = Color(0xFF66BB6A),
    error = Color(0xFFEF5350),
    warning = Color(0xFFFFB74D),
    info = Color(0xFF42A5F5),
    cardBackground = Color(0xFF3A3A3A),
    cardBackgroundHover = Color(0xFF424242),
    inputBackground = Color(0xFF424242),
    selectedBackground = Color(0xFF4A4A4A),
    overlayBackground = Color(0xC0000000)
)
val PitchBlackScheme = AppColorScheme(
    primary = Color(0xFF90CAF9),
    onPrimary = Color.Black,
    primaryContainer = Color(0xFF64B5F6),
    background = Color(0xFF000000),
    surface = Color(0xFF0A0A0A),
    surfaceVariant = Color(0xFF1A1A1A),
    surfaceTertiary = Color(0xFF242424),
    textPrimary = Color(0xFFEEEEEE),
    textSecondary = Color(0xFFBDBDBD),
    textTertiary = Color(0xFF9E9E9E),
    textDisabled = Color(0xFF616161),
    border = Color(0xFF2A2A2A),
    borderFocused = Color(0xFF424242),
    divider = Color(0xFF1A1A1A),
    interactive = Color(0xFF90CAF9),
    interactiveHover = Color(0xFF64B5F6),
    interactivePressed = Color(0xFF42A5F5),
    success = Color(0xFF66BB6A),
    error = Color(0xFFEF5350),
    warning = Color(0xFFFFB74D),
    info = Color(0xFF42A5F5),
    cardBackground = Color(0xFF0A0A0A),
    cardBackgroundHover = Color(0xFF1A1A1A),
    inputBackground = Color(0xFF1A1A1A),
    selectedBackground = Color(0xFF242424),
    overlayBackground = Color(0xE0000000)
)
val CharcoalScheme = AppColorScheme(
    primary = Color(0xFF90CAF9),
    onPrimary = Color(0xFF1C1C1C),
    primaryContainer = Color(0xFF64B5F6),
    background = Color(0xFF1C1C1C),
    surface = Color(0xFF252525),
    surfaceVariant = Color(0xFF2E2E2E),
    surfaceTertiary = Color(0xFF383838),
    textPrimary = Color(0xFFEEEEEE),
    textSecondary = Color(0xFFBDBDBD),
    textTertiary = Color(0xFF9E9E9E),
    textDisabled = Color(0xFF757575),
    border = Color(0xFF404040),
    borderFocused = Color(0xFF5A5A5A),
    divider = Color(0xFF2E2E2E),
    interactive = Color(0xFF90CAF9),
    interactiveHover = Color(0xFF64B5F6),
    interactivePressed = Color(0xFF42A5F5),
    success = Color(0xFF66BB6A),
    error = Color(0xFFEF5350),
    warning = Color(0xFFFFB74D),
    info = Color(0xFF42A5F5),
    cardBackground = Color(0xFF252525),
    cardBackgroundHover = Color(0xFF2E2E2E),
    inputBackground = Color(0xFF2E2E2E),
    selectedBackground = Color(0xFF383838),
    overlayBackground = Color(0xC0000000)
)
enum class AppTheme(val displayName: String, val colorScheme: AppColorScheme) {
    CLASSIC_WHITE("Classic White", ClassicWhiteScheme),
    WARM_CREAM("Warm Cream", WarmCreamScheme),
    DARK_GRAY("Dark Gray", DarkGrayScheme),
    PITCH_BLACK("Pitch Black", PitchBlackScheme),
    CHARCOAL("Charcoal", CharcoalScheme);
    companion object {
        fun fromName(name: String): AppTheme {
            return entries.find { it.name == name } ?: CLASSIC_WHITE
        }
    }
}
